extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-go
  container: go
pipelines:
  pullRequest:
    build:
      dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME
      steps:
      - sh: make linux
  release:
    setVersion:
      dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME
      steps:
      - sh: echo \$(jx-release-version) > VERSION
        comment: so we can retrieve the version in later steps
      - sh: jx step tag --version \$(cat VERSION)
    build:
      dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME
      steps:
      - sh: make build
