extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-go
  container: go
pipelines:
  release:
    setVersion:
      steps:
      - sh: jx step next-version --use-git-tag-only --tag
        name: tag-version
      - sh: jx step changelog --verbose --version ${VERSION} --rev ${PULL_BASE_SHA}
        name: release-version
